In [1]:
#Normal List Element
x = [3 ,4 , 7]
print(x)
type(x)

[3, 4, 7]


list

In [3]:
conda install opencv-python

Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

Note: you may need to restart the kernel to use updated packages.



PackagesNotFoundError: The following packages are not available from current channels:

  - opencv-python

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.




In [11]:
#import numpy library
import numpy as np

y = np.array([3,4,7] )
print(y)
type(y)
print(y.shape)

[3 4 7]
(3,)


In [6]:
#converting List to Array

z = np.array(x)
print(z)

[3 4 7]


In [12]:
#Creating 2D Matrix

List2D = [[1 , 2  , 5 ] , [4 ,5 , 6] , [7 , 8, 9]]
Array2D = np.array(List2D)
Array2D

array([[1, 2, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#To avoid creating array manually


X = np.arange( 0 , 10 , 2)
X

array([0, 2, 4, 6, 8])

In [19]:
#Add Step size

#To add only even numbers from 0 to 10

Y = np.arange(0 , 11 , 2)
Y

array([ 0,  2,  4,  6,  8, 10])

Question : To create an array  3 , 9 , 15 , 21 , 27

In [25]:
X = np.arange(3 ,33 ,6)
print(X)

[ 3  9 15 21 27]


In [26]:
#To generate array of Zeros(1-D)

X = np.zeros(7)
X

array([0., 0., 0., 0., 0., 0., 0.])

In [28]:
#To generate array of Zeros(2-D)

X = np.zeros((3,6))
X

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
#To generate array of Ones(1-D)

X = np.ones((3))
X

array([1., 1., 1.])

In [30]:
#To generate array of Ones(2-D)

X = np.ones((3 , 5))
X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
#To get evenly spaced values between 2 values

X = np.linspace( 0.6 ,20.9 ,5)
X

array([ 0.6  ,  5.675, 10.75 , 15.825, 20.9  ])

In [37]:
#To create identity matrix
i = np.eye(2)
print(i)

i = np.eye(3)
print(i)
print(i.dtype)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64


In [44]:
#To create 1 -D array with a random distribution

X = np.random.rand(4)
X

array([0.8381418 , 0.04565318, 0.11305512, 0.90168187])

In [45]:
#To create 2 -D array with a random distribution

X = np.random.rand(4,2)
X

array([[0.23213504, 0.93516331],
       [0.62310537, 0.57900731],
       [0.85380837, 0.63788295],
       [0.2886278 , 0.65826459]])

In [54]:
#Create an array of Random numbers
X = np.random.randint( 0 ,100, 5)
X
print(X.shape)

(5,)


In [56]:
#To reshape an array

X = np.arange(0,25)
print(X.shape)
print(X)

print(X.reshape(5,5))

(25,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [65]:
#To find min and max values from array

X = np.random.randint(1 , 100 , 10)
print(X)
print(X.max())
print(X.min())
#Location of Max value
print("Max value at :")
print(X.argmax())

#Location of Min value
print(X.argmin())

[75 29 27 80 70 98 55 63 90 98]
98
27
Max value at :
5
2


In [64]:
#To find shape of array

print(X.shape)

(10,)


In [ ]:
#To find datatype of elements of Array

print(X.dtype)